### ISSUE TITLE
Private Pen?

### ISSUE THREAD

**Issue by AntoineW** [workeffortwaste/gsap-video-export#1]
Hey,
First I want to say that this is an awesome idea and a super handy tool 😍

I just tried it with a private CodePen but it keeps failing. The same pen saved as public works fine.
Would it be possible to make it work with private pens as well?

Thanks 🙏

**Comment by workeffortwaste** [comment]
This should now work in version 1.0.2. 👍

**Comment by AntoineW** [comment]
Awesome, thank you!
