### ISSUE TITLE
Export custom timeline not codepen

### ISSUE THREAD

**Issue by ahmed-adly-khalil** [workeffortwaste/gsap-video-export#2]
Hello Hello 👋 
I came across this awesome project through the Amazing [Pete Barr](https://twitter.com/petebarr) feed, is there a way to export from a JS file that has already the timeline not from codepen? i mean i have a JS file that has the timeline and want to add a button to export it from the same file.

Not really an issue, just a question :) 

Have a great day 
A

**Comment by workeffortwaste** [comment]
It's not just limited to CodePen URLs, you can use any HTML URL that contains a GSAP animation/timeline.
