### ISSUE TITLE
Node js version

### ISSUE THREAD

**Issue by galipmedia** [workeffortwaste/gsap-video-export#4]
Is it possible to run this from node js or only CLI ? I had a brief look at the code and it wasn't immediately obvious how it would be done. It would be very handy if it could be run programmatically.

**Comment by workeffortwaste** [comment]
It's not currently possible to run it outside the CLI but it's high on my to-do list to add support for that.

I'll see if I can get it done this week or next.

**Comment by workeffortwaste** [comment]
@galipmedia Only took two years but it's in the latest version (2.0.0). 😂
