### ISSUE TITLE
Video render

### ISSUE THREAD

**Issue by hoprikoma** [workeffortwaste/gsap-video-export#7]
Hi, 
I just tested your website on a webpage I just created, I use video HTML tag, but when rendering the video is going very very fast.
There is a solution to stabilise video fps ?
Thank you

**Comment by workeffortwaste** [comment]
Are you able to share the command you used, so I can see your settings?

**Comment by workeffortwaste** [comment]
As the video component is not controlled by the GSAP timeline it isn't captured properly when gsap-video-export manipulates the animation timeline.

If you use the `timeweb` option for advancing frames it will instead manipulate the browser to control time globally.

```
gsap-video-export localhost -a timeweb
```

Let me know how this works for you.

**Comment by hoprikoma** [comment]
After installing the module and execute command, it log all the timeweb script into my terminal, but the render work so it's good :D Thank you so much

**Comment by workeffortwaste** [comment]
Glad it works. Looks like I left in a debug log for timeweb, which is why you saw the script in terminal. I'll remove that in the next release.
